import type { Metadata } from 'next';
import { DefaultProviders } from '@/lib';

import './globals.css';

export const metadata: Metadata = {
  title: 'Robin',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DefaultProviders>
          <main>{children}</main>
        </DefaultProviders>
      </body>
    </html>
  );
}
